SELECT  TICKET_NUMERO, TICKET_DET_CANTIDAD, TICKET_DET_PRECIO, TICKET_DET_CANTIDAD, TICKET_TOTAL_TICKET , TICKET_TOTAL_DESCUENTO_APLICADO, TICKET_TOTAL_DESCUENTO_APLICADO_MP
FROM gd_esquema.Maestra
order by TICKET_NUMERO

SELECT *
FROM gd_esquema.Maestra
where TICKET_NUMERO = '1351318358'

SELECT TICKET_NUMERO, count(TICKET_NUMERO) cantRepeticiones, sum(TICKET_TOTAL_ENVIO)
FROM gd_esquema.Maestra
group by TICKET_NUMERO
having sum(TICKET_TOTAL_ENVIO) > 1
order by 2


SELECT TICKET_NUMERO, TICKET_DET_TOTAL, TICKET_SUBTOTAL_PRODUCTOS, TICKET_TOTAL_DESCUENTO_APLICADO, TICKET_TOTAL_DESCUENTO_APLICADO_MP, TICKET_TOTAL_ENVIO, TICKET_TOTAL_TICKET
FROM gd_esquema.Maestra
where TICKET_NUMERO = '1354097265' /*DESPUES VER por que este tiene un null sin costo de envio */

/*===*/
SELECT TICKET_NUMERO, TICKET_DET_TOTAL, TICKET_SUBTOTAL_PRODUCTOS, TICKET_TOTAL_DESCUENTO_APLICADO, TICKET_TOTAL_DESCUENTO_APLICADO_MP, TICKET_TOTAL_ENVIO, TICKET_TOTAL_TICKET
FROM gd_esquema.Maestra
where TICKET_NUMERO = '1351422891' /*DESPUES VER por que este tiene dos null con costo de envio*/


SELECT *
FROM gd_esquema.Maestra
where TICKET_NUMERO = '1351422891'

SELECT TICKET_NUMERO, TICKET_DET_CANTIDAD, TICKET_DET_TOTAL, PRODUCTO_NOMBRE,PRODUCTO_DESCRIPCION, PRODUCTO_CATEGORIA, PROMO_CODIGO, PROMO_APLICADA_DESCUENTO ,PROMOCION_DESCRIPCION
FROM gd_esquema.Maestra
where TICKET_NUMERO = '1351422891'/* 'ver el producto categoria terminado en 16    OR TICKET_NUMERO = '1354097265' OR TICKET_NUMERO = '1351318809*/
order by 1


SELECT TICKET_NUMERO, count(TICKET_DET_CANTIDAD), count(PROMO_CODIGO), count(PROMOCION_DESCRIPCION)
FROM gd_esquema.Maestra
group by TICKET_NUMERO
order by 1


/*otro analizis*/
SELECT TICKET_NUMERO, TICKET_DET_CANTIDAD, PAGO_FECHA, PAGO_IMPORTE, PAGO_MEDIO_PAGO, PAGO_TIPO_MEDIO_PAGO, PAGO_TARJETA_NRO, PAGO_TARJETA_CUOTAS, PAGO_TARJETA_FECHA_VENC, PAGO_DESCUENTO_APLICADO
FROM gd_esquema.Maestra
where TICKET_NUMERO = '1351422891' /*hay una fila de puron nulls rari*/
order by 1








SELECT *
FROM gd_esquema.Maestra
where TICKET_NUMERO = '1354097265'/* 'ver el producto categoria terminado en 16    OR TICKET_NUMERO = '1354097265' OR TICKET_NUMERO = '1351318809*/
order by 1


SELECT TICKET_NUMERO,TICKET_DET_CANTIDAD, TICKET_DET_PRECIO ,PROMO_APLICADA_DESCUENTO, PROMO_CODIGO
FROM gd_esquema.Maestra
where PROMO_CODIGO = '79'/* 'ver el producto categoria terminado en 16    OR TICKET_NUMERO = '1354097265' OR TICKET_NUMERO = '1351318809*/
order by 1


